<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<h2>Welcome</h2>
<p><strong><a href="http://www.uk.amsat.org/">AMSAT-UK</a></strong> is working on a new amateur satellite project – <em><strong>The FUNcube Project</strong></em> – that features a 435 to 145 MHz Linear Transponder for SSB/CW operation. The project has received major initial funding from the Radio Communications Foundation (RCF) and is being developed in collaboration with ISIS-Innovative Solutions in Space BV.</p>
<p><strong>FUNcube-1</strong> is a complete educational single CubeSat project with the goal of enthusing and educating young people about radio, space, physics and electronics.</p>
<p><em><strong>FUNcube-2 on UKube</strong></em> comprises of a set of FUNcube boards that will fly as part of the separate UKube triple cubesat and has identical goals.</p>
<p>They will support the educational Science, Technology, Engineering and Maths (STEM) initiatives and provide an additional resource for the <strong>GB4FUN</strong> Mobile Communications Centre.</p>
<p>The target audience consists of primary and secondary school pupils and the FUNcubes will feature a 145 MHz telemetry beacon that will provide a strong signal for the pupils to receive.</p>
<p>A simple receiver board has also been developed. The FUNcube dongle connects to the USB port of a laptop to display telemetry and messages in an visually interesting and stimulating way.</p>
<p>The satellites will contain a materials science experiment, from which the school students can receive telemetry data which they can compare to the results they obtained from similar reference experiments in the classroom.</p>
<p>FUNcube is the first CubeSat project that will benefit this group.</p>
<p>It is anticipated that the FUNcubes will be launched into a Sun Synchronous Low Earth Orbit about 600-700km above the earth using one of the many launch opportunities that exist for CubeSat missions. In such an orbit the satellite passes over Europe approximately 3 times in the morning, and 3 in the evening, every day, perhaps allowing the morning passes to be used for educational purposes and the evening passes for Amateur Radio communications.</p>
<p><a href="http://funcubeblog.files.wordpress.com/2010/02/poster_corrected-logoredsep103.png"><img class="alignright size-medium wp-image-611" title="poster_corrected logoredsep10" src="http://funcubeblog.files.wordpress.com/2010/02/poster_corrected-logoredsep103.png?w=263&#038;h=300" alt="" width="263" height="300" /></a></p>
<p>The FUNcubes will also carry a UHF to VHF linear transponder that will have approx 500mW PEP output and which can be used by Radio Amateurs worldwide for SSB and CW communications.</p>
<p>Measuring just 10cm x 10cm x 10cm, and with a mass of less than 1kg, FUNcube-1 will be the smallest ever satellite to carry a linear transponder and the choice of frequencies will enable Radio Amateurs to use their existing VO-52, DO-64, HO68 and similar stations.</p>
<p>A key feature of the satellite is the absence of an over complicated, multi-faceted, multi-tasking On-Board Computer. For reliability and maximum power efficiency, the design has been kept as straight-forward as possible with satellite control being achieved using simple commands.</p>
<p>AMSAT-UK has more than 350 individual members and is one of more than 20 such groups worldwide. AMSAT-UK teams have provided hardware for more than 10 satellites over the past 35+ years including SSETI Express in 2005.</p>
<p>They are presently involved with the development of hardware and software for a number of satellite projects including the European Student Earth Orbiter (ESEO), P3E, the Columbus module on the ISS and also the GENSO Ground station network.</p>
<p>The <strong>Radio Communications Foundation</strong> is a Registered Charity (Number 1100694) set up in 2003 to fund efforts to bring the wonders of radio into the classrooms, universities and any other public place where hands on demonstration can influence understanding.</p>
<p>The RCF funding for FUNcube is made possible through the generous bequest from a “silent key” who wanted the hobby that he loved brought to the attention of others. Any one wanting to make a bequest in their Will so that their name can live on in the hobby, or anyone simply wanting to make a donation, should visit <a href="http://www.commsfoundation.org/">http://www.commsfoundation.org/</a>.</p>
<p>FUNcube contact: Graham Shirville G3VZV email g.shirville at btinternet.com</p>
